// AUTH

export const SET_AUTH_LOADER = "SET_AUTH_LOADER";
export const SET_USER = "SET_USER";
export const SET_AUTH_RES_ERROR = "SET_AUTH_RES_ERROR";
export const SET_AUTH_RES_SUCCESS = "SET_AUTH_RES_SUCCESS";
export const CLEAR_AUTH_RES = "CLEAR_AUTH_RES";
export const CLEAR_AUTH = "CLEAR_AUTH";

// Chat

export const SET_SOCKET = "SET_SOCKET";
export const SET_CHAT_LOADER = "SET_CHAT_LOADER";
export const SET_CONTACTS = "SET_CONTACTS";
export const SET_CONVERSATIONS = "SET_CONVERSATIONS";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const SET_SELECTED_CONVERSATIONS_ID = "SET_SELECTED_CONVERSATIONS_ID";
export const SET_CHAT_RES_ERROR = "SET_CHAT_RES_ERROR";
export const SET_CHAT_RES_SUCCESS = "SET_CHAT_RES_SUCCESS";
export const CLEAR_CHAT_RES = "CLEAR_CHAT_RES";
export const CLEAR_CHAT = "CLEAR_CHAT";
